### ISSUE TITLE
PHP 8.0 compatibility?

### ISSUE THREAD

**Issue by HarasimowiczKamil** [api-platform/admin-pack#3]
**API Platform version(s) affected**: x.y.z

**Description**  

```
- Root composer.json requires api-platform/admin-pack ^1.0 -> satisfiable by api-platform/admin-pack[v1.0.0].
- api-platform/admin-pack v1.0.0 requires php ^7.0 -> your php version (8.0.1) does not satisfy that requirement.
```
**How to reproduce**  

Install `api-platform/admin-pack` with php8.0

**Possible Solution**  

Updating composer.json is probably enough

**Additional Context**

**Comment by dunglas** [comment]
Fixed by #5.
